name: "${name}"
main: "${group}.Pl3xMapWarps"
version: "${version}"
api-version: "${apiVersion}"
load: "POSTWORLD"
authors: ${authors}
description: "${description}"
website: "${website}"

softdepend:
  - Pl3xMap
  - Essentials
  - PlayerWarps